version: "3.9"
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    restart: always

  redis:
    image: redis/redis-stack-server:6.2.6-v4
    ports:
      - "6379:6379"
    restart: always

  # Microservice images
  core-service:
    image: 127.0.0.1:5000/ds-project/core
    build: ./core
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=${CORE_MONGO_URI}
      - REDIS_URI=${CORE_REDIS_URI}
    depends_on:
      - mongo
      - redis

  gateway-service:
    image: 127.0.0.1:5000/ds-project/gateway
    build: ./gateway
    ports:
      - "3000:3000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    depends_on:
      - core-service

  cart-service:
    image: 127.0.0.1:5000/ds-project/cart
    build: ./cart
    ports:
      - "3002:3004"
    environment:
      - MONGO_URI=${CART_MONGO_URI}
    depends_on:
      - mongo

  item-review-service:
    image: 127.0.0.1:5000/ds-project/item-review
    build: ./item_review
    ports:
      - "3006:3006"
    environment:
      - MONGO_URI=${ITEM_REVIEW_MONGO_URI}
    depends_on:
      - mongo

  # order-payment-service:
  # image: 127.0.0.1:5000/ds-project
  #   build: ./order_payment
  #   ports:
  #     - "3003:3003"
  #   environment:
  #     - MONGO_URI=${ORDER_PAYMENT_MONGO_URI}
  #   depends_on:
  #     - mongo
