services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    restart: always

  rabbitmq:
    image: rabbitmq:3.11.9-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  redis:
    image: redis:alpine3.17
    ports:
      - "6379:6379"
    restart: always

  auth-service:
    build: ./auth
    ports:
      - "3001:3001"
    env_file: ./auth/.env
    depends_on:
      - mongo
      - rabbitmq
      - redis
    restart: always

  comms-service:
    build: /comm
    ports:
      - "3002:3002"
    env_file: ./comm/.env
    depends_on:
      - mongo
      - rabbitmq
    restart: always
